// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kernel/kernel.proto

package kernel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorType     string                 `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnActorRequest) Reset() {
	*x = SpawnActorRequest{}
	mi := &file_kernel_kernel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnActorRequest) ProtoMessage() {}

func (x *SpawnActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnActorRequest.ProtoReflect.Descriptor instead.
func (*SpawnActorRequest) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnActorRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *SpawnActorRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type SpawnActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnActorResponse) Reset() {
	*x = SpawnActorResponse{}
	mi := &file_kernel_kernel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnActorResponse) ProtoMessage() {}

func (x *SpawnActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnActorResponse.ProtoReflect.Descriptor instead.
func (*SpawnActorResponse) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{1}
}

func (x *SpawnActorResponse) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetActorId string                 `protobuf:"bytes,1,opt,name=target_actor_id,json=targetActorId,proto3" json:"target_actor_id,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_kernel_kernel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetTargetActorId() string {
	if x != nil {
		return x.TargetActorId
	}
	return ""
}

func (x *SendMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SendMessageRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SendMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_kernel_kernel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{3}
}

type QueryStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateRequest) Reset() {
	*x = QueryStateRequest{}
	mi := &file_kernel_kernel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateRequest) ProtoMessage() {}

func (x *QueryStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateRequest.ProtoReflect.Descriptor instead.
func (*QueryStateRequest) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{4}
}

func (x *QueryStateRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *QueryStateRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type QueryStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       [][]byte               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateResponse) Reset() {
	*x = QueryStateResponse{}
	mi := &file_kernel_kernel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateResponse) ProtoMessage() {}

func (x *QueryStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateResponse.ProtoReflect.Descriptor instead.
func (*QueryStateResponse) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{5}
}

func (x *QueryStateResponse) GetResults() [][]byte {
	if x != nil {
		return x.Results
	}
	return nil
}

type SubscribeStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamName    string                 `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeStreamRequest) Reset() {
	*x = SubscribeStreamRequest{}
	mi := &file_kernel_kernel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStreamRequest) ProtoMessage() {}

func (x *SubscribeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStreamRequest.ProtoReflect.Descriptor instead.
func (*SubscribeStreamRequest) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeStreamRequest) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *SubscribeStreamRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *SubscribeStreamRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_kernel_kernel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamName    string                 `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_kernel_kernel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{8}
}

func (x *PublishEventRequest) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *PublishEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishEventRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *PublishEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_kernel_kernel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_kernel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_kernel_kernel_proto_rawDescGZIP(), []int{9}
}

func (x *PublishEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_kernel_kernel_proto protoreflect.FileDescriptor

const file_kernel_kernel_proto_rawDesc = "" +
	"\n" +
	"\x13kernel/kernel.proto\x12\fastra.kernel\"J\n" +
	"\x11SpawnActorRequest\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x01 \x01(\tR\tactorType\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\"/\n" +
	"\x12SpawnActorResponse\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"\x91\x01\n" +
	"\x12SendMessageRequest\x12&\n" +
	"\x0ftarget_actor_id\x18\x01 \x01(\tR\rtargetActorId\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x15\n" +
	"\x13SendMessageResponse\"\xb8\x01\n" +
	"\x11QueryStateRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12F\n" +
	"\afilters\x18\x02 \x03(\v2,.astra.kernel.QueryStateRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x12QueryStateResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\fR\aresults\"\x81\x01\n" +
	"\x16SubscribeStreamRequest\x12\x1f\n" +
	"\vstream_name\x18\x01 \x01(\tR\n" +
	"streamName\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\"~\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x8a\x01\n" +
	"\x13PublishEventRequest\x12\x1f\n" +
	"\vstream_name\x18\x01 \x01(\tR\n" +
	"streamName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"1\n" +
	"\x14PublishEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId2\xac\x03\n" +
	"\rKernelService\x12O\n" +
	"\n" +
	"SpawnActor\x12\x1f.astra.kernel.SpawnActorRequest\x1a .astra.kernel.SpawnActorResponse\x12R\n" +
	"\vSendMessage\x12 .astra.kernel.SendMessageRequest\x1a!.astra.kernel.SendMessageResponse\x12O\n" +
	"\n" +
	"QueryState\x12\x1f.astra.kernel.QueryStateRequest\x1a .astra.kernel.QueryStateResponse\x12N\n" +
	"\x0fSubscribeStream\x12$.astra.kernel.SubscribeStreamRequest\x1a\x13.astra.kernel.Event0\x01\x12U\n" +
	"\fPublishEvent\x12!.astra.kernel.PublishEventRequest\x1a\".astra.kernel.PublishEventResponseB\x14Z\x12astra/proto/kernelb\x06proto3"

var (
	file_kernel_kernel_proto_rawDescOnce sync.Once
	file_kernel_kernel_proto_rawDescData []byte
)

func file_kernel_kernel_proto_rawDescGZIP() []byte {
	file_kernel_kernel_proto_rawDescOnce.Do(func() {
		file_kernel_kernel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_kernel_proto_rawDesc), len(file_kernel_kernel_proto_rawDesc)))
	})
	return file_kernel_kernel_proto_rawDescData
}

var file_kernel_kernel_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_kernel_kernel_proto_goTypes = []any{
	(*SpawnActorRequest)(nil),      // 0: astra.kernel.SpawnActorRequest
	(*SpawnActorResponse)(nil),     // 1: astra.kernel.SpawnActorResponse
	(*SendMessageRequest)(nil),     // 2: astra.kernel.SendMessageRequest
	(*SendMessageResponse)(nil),    // 3: astra.kernel.SendMessageResponse
	(*QueryStateRequest)(nil),      // 4: astra.kernel.QueryStateRequest
	(*QueryStateResponse)(nil),     // 5: astra.kernel.QueryStateResponse
	(*SubscribeStreamRequest)(nil), // 6: astra.kernel.SubscribeStreamRequest
	(*Event)(nil),                  // 7: astra.kernel.Event
	(*PublishEventRequest)(nil),    // 8: astra.kernel.PublishEventRequest
	(*PublishEventResponse)(nil),   // 9: astra.kernel.PublishEventResponse
	nil,                            // 10: astra.kernel.QueryStateRequest.FiltersEntry
}
var file_kernel_kernel_proto_depIdxs = []int32{
	10, // 0: astra.kernel.QueryStateRequest.filters:type_name -> astra.kernel.QueryStateRequest.FiltersEntry
	0,  // 1: astra.kernel.KernelService.SpawnActor:input_type -> astra.kernel.SpawnActorRequest
	2,  // 2: astra.kernel.KernelService.SendMessage:input_type -> astra.kernel.SendMessageRequest
	4,  // 3: astra.kernel.KernelService.QueryState:input_type -> astra.kernel.QueryStateRequest
	6,  // 4: astra.kernel.KernelService.SubscribeStream:input_type -> astra.kernel.SubscribeStreamRequest
	8,  // 5: astra.kernel.KernelService.PublishEvent:input_type -> astra.kernel.PublishEventRequest
	1,  // 6: astra.kernel.KernelService.SpawnActor:output_type -> astra.kernel.SpawnActorResponse
	3,  // 7: astra.kernel.KernelService.SendMessage:output_type -> astra.kernel.SendMessageResponse
	5,  // 8: astra.kernel.KernelService.QueryState:output_type -> astra.kernel.QueryStateResponse
	7,  // 9: astra.kernel.KernelService.SubscribeStream:output_type -> astra.kernel.Event
	9,  // 10: astra.kernel.KernelService.PublishEvent:output_type -> astra.kernel.PublishEventResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_kernel_kernel_proto_init() }
func file_kernel_kernel_proto_init() {
	if File_kernel_kernel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_kernel_proto_rawDesc), len(file_kernel_kernel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernel_kernel_proto_goTypes,
		DependencyIndexes: file_kernel_kernel_proto_depIdxs,
		MessageInfos:      file_kernel_kernel_proto_msgTypes,
	}.Build()
	File_kernel_kernel_proto = out.File
	file_kernel_kernel_proto_goTypes = nil
	file_kernel_kernel_proto_depIdxs = nil
}
