// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: llm/llm.proto

package llm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMRouter_Complete_FullMethodName = "/astra.llm.LLMRouter/Complete"
)

// LLMRouterClient is the client API for LLMRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMRouterClient interface {
	Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
}

type lLMRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMRouterClient(cc grpc.ClientConnInterface) LLMRouterClient {
	return &lLMRouterClient{cc}
}

func (c *lLMRouterClient) Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, LLMRouter_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMRouterServer is the server API for LLMRouter service.
// All implementations must embed UnimplementedLLMRouterServer
// for forward compatibility.
type LLMRouterServer interface {
	Complete(context.Context, *CompletionRequest) (*CompletionResponse, error)
	mustEmbedUnimplementedLLMRouterServer()
}

// UnimplementedLLMRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMRouterServer struct{}

func (UnimplementedLLMRouterServer) Complete(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedLLMRouterServer) mustEmbedUnimplementedLLMRouterServer() {}
func (UnimplementedLLMRouterServer) testEmbeddedByValue()                   {}

// UnsafeLLMRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMRouterServer will
// result in compilation errors.
type UnsafeLLMRouterServer interface {
	mustEmbedUnimplementedLLMRouterServer()
}

func RegisterLLMRouterServer(s grpc.ServiceRegistrar, srv LLMRouterServer) {
	// If the following call panics, it indicates UnimplementedLLMRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMRouter_ServiceDesc, srv)
}

func _LLMRouter_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMRouterServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMRouter_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMRouterServer).Complete(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMRouter_ServiceDesc is the grpc.ServiceDesc for LLMRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astra.llm.LLMRouter",
	HandlerType: (*LLMRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _LLMRouter_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/llm.proto",
}
