// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: memory/memory.proto

package memory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MemoryType    string                 `protobuf:"bytes,2,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []byte                 `protobuf:"bytes,4,opt,name=embedding,proto3" json:"embedding,omitempty"` // optional; 1536*4 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMemoryRequest) Reset() {
	*x = WriteMemoryRequest{}
	mi := &file_memory_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMemoryRequest) ProtoMessage() {}

func (x *WriteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMemoryRequest.ProtoReflect.Descriptor instead.
func (*WriteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{0}
}

func (x *WriteMemoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WriteMemoryRequest) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *WriteMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WriteMemoryRequest) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type WriteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMemoryResponse) Reset() {
	*x = WriteMemoryResponse{}
	mi := &file_memory_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMemoryResponse) ProtoMessage() {}

func (x *WriteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMemoryResponse.ProtoReflect.Descriptor instead.
func (*WriteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{1}
}

func (x *WriteMemoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchMemoriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	QueryEmbedding []byte                 `protobuf:"bytes,2,opt,name=query_embedding,json=queryEmbedding,proto3" json:"query_embedding,omitempty"` // optional; 1536 floats
	TopK           int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchMemoriesRequest) Reset() {
	*x = SearchMemoriesRequest{}
	mi := &file_memory_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesRequest) ProtoMessage() {}

func (x *SearchMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesRequest.ProtoReflect.Descriptor instead.
func (*SearchMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMemoriesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SearchMemoriesRequest) GetQueryEmbedding() []byte {
	if x != nil {
		return x.QueryEmbedding
	}
	return nil
}

func (x *SearchMemoriesRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type MemoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MemoryType    string                 `protobuf:"bytes,3,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []byte                 `protobuf:"bytes,5,opt,name=embedding,proto3" json:"embedding,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryItem) Reset() {
	*x = MemoryItem{}
	mi := &file_memory_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryItem) ProtoMessage() {}

func (x *MemoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryItem.ProtoReflect.Descriptor instead.
func (*MemoryItem) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryItem) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemoryItem) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *MemoryItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryItem) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type SearchMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MemoryItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoriesResponse) Reset() {
	*x = SearchMemoriesResponse{}
	mi := &file_memory_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesResponse) ProtoMessage() {}

func (x *SearchMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesResponse.ProtoReflect.Descriptor instead.
func (*SearchMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMemoriesResponse) GetItems() []*MemoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_memory_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{5}
}

func (x *GetMemoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MemoryType    string                 `protobuf:"bytes,3,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []byte                 `protobuf:"bytes,5,opt,name=embedding,proto3" json:"embedding,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_memory_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_memory_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMemoryResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetMemoryResponse) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *GetMemoryResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetMemoryResponse) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_memory_memory_proto protoreflect.FileDescriptor

const file_memory_memory_proto_rawDesc = "" +
	"\n" +
	"\x13memory/memory.proto\x12\fastra.memory\"\x88\x01\n" +
	"\x12WriteMemoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmemory_type\x18\x02 \x01(\tR\n" +
	"memoryType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x04 \x01(\fR\tembedding\"%\n" +
	"\x13WriteMemoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"p\n" +
	"\x15SearchMemoriesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fquery_embedding\x18\x02 \x01(\fR\x0equeryEmbedding\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"\x90\x01\n" +
	"\n" +
	"MemoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmemory_type\x18\x03 \x01(\tR\n" +
	"memoryType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x05 \x01(\fR\tembedding\"H\n" +
	"\x16SearchMemoriesResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.astra.memory.MemoryItemR\x05items\"\"\n" +
	"\x10GetMemoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x97\x01\n" +
	"\x11GetMemoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmemory_type\x18\x03 \x01(\tR\n" +
	"memoryType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x05 \x01(\fR\tembedding2\x8e\x02\n" +
	"\rMemoryService\x12R\n" +
	"\vWriteMemory\x12 .astra.memory.WriteMemoryRequest\x1a!.astra.memory.WriteMemoryResponse\x12[\n" +
	"\x0eSearchMemories\x12#.astra.memory.SearchMemoriesRequest\x1a$.astra.memory.SearchMemoriesResponse\x12L\n" +
	"\tGetMemory\x12\x1e.astra.memory.GetMemoryRequest\x1a\x1f.astra.memory.GetMemoryResponseB\x14Z\x12astra/proto/memoryb\x06proto3"

var (
	file_memory_memory_proto_rawDescOnce sync.Once
	file_memory_memory_proto_rawDescData []byte
)

func file_memory_memory_proto_rawDescGZIP() []byte {
	file_memory_memory_proto_rawDescOnce.Do(func() {
		file_memory_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_memory_proto_rawDesc), len(file_memory_memory_proto_rawDesc)))
	})
	return file_memory_memory_proto_rawDescData
}

var file_memory_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_memory_memory_proto_goTypes = []any{
	(*WriteMemoryRequest)(nil),     // 0: astra.memory.WriteMemoryRequest
	(*WriteMemoryResponse)(nil),    // 1: astra.memory.WriteMemoryResponse
	(*SearchMemoriesRequest)(nil),  // 2: astra.memory.SearchMemoriesRequest
	(*MemoryItem)(nil),             // 3: astra.memory.MemoryItem
	(*SearchMemoriesResponse)(nil), // 4: astra.memory.SearchMemoriesResponse
	(*GetMemoryRequest)(nil),       // 5: astra.memory.GetMemoryRequest
	(*GetMemoryResponse)(nil),      // 6: astra.memory.GetMemoryResponse
}
var file_memory_memory_proto_depIdxs = []int32{
	3, // 0: astra.memory.SearchMemoriesResponse.items:type_name -> astra.memory.MemoryItem
	0, // 1: astra.memory.MemoryService.WriteMemory:input_type -> astra.memory.WriteMemoryRequest
	2, // 2: astra.memory.MemoryService.SearchMemories:input_type -> astra.memory.SearchMemoriesRequest
	5, // 3: astra.memory.MemoryService.GetMemory:input_type -> astra.memory.GetMemoryRequest
	1, // 4: astra.memory.MemoryService.WriteMemory:output_type -> astra.memory.WriteMemoryResponse
	4, // 5: astra.memory.MemoryService.SearchMemories:output_type -> astra.memory.SearchMemoriesResponse
	6, // 6: astra.memory.MemoryService.GetMemory:output_type -> astra.memory.GetMemoryResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_memory_memory_proto_init() }
func file_memory_memory_proto_init() {
	if File_memory_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_memory_proto_rawDesc), len(file_memory_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_memory_proto_goTypes,
		DependencyIndexes: file_memory_memory_proto_depIdxs,
		MessageInfos:      file_memory_memory_proto_msgTypes,
	}.Build()
	File_memory_memory_proto = out.File
	file_memory_memory_proto_goTypes = nil
	file_memory_memory_proto_depIdxs = nil
}
